spring:
  application:
    name: yupao-backed-master
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi?serverTimezone=Asia/Shanghai
    username: root
    password: root
  # session 失效时间
  session:
    timeout: 86400
    #session存储位置  默认为none(服务器)
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
    # Redis数据库索引（默认为0）
    database: 2
    #密码
    password: 123456
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
